#!/bin/bash

{
  mkdir -p tools
  mv branch.c checkbits.sh cols.c echo.c pandoc_headers.c tools/

  sh ./configure.sh --prefix=$PREFIX
  make libmarkdown

  if ! [ -z $PREFIX ]; then
    mark install
  fi

  sed 's/<markdown.h>/<discount\/markdown.h>/g' -i *.c

  sed 's/<mkdio.h>/<discount\/mkdio.h>/g' -i *.c

  sed "s/VERSION/$(cat VERSION)/g" -i version.c
  sed 's/BRANCH/""/g' -i version.c
}
